### ISSUE TITLE
Support for arrays of Nodes

### ISSUE THREAD

**Issue by jpg0** [microclimates/homie-device#7]
Ideally I'd like to use a homie node array for my device, however it's not supported here.

I took a quick look at what it would take to implement and decided not to go ahead myself as it may introduce significant rework on the exist codebase.

I realised that the reason for this is a lacking abstraction; that between the interface/specification and the objects/realisations of them. Currently they are one and the same: the API allows constructing objects/interfaces and sending/receiving data. When using node arrays, there is a single specification for multiple instances of a node. This is problematic with the existing API because (for example) an event describing a state update is received on the API which describes the interface, whereas the update should be applied to a specific instance of it.

If you have a specific view on how it should be implemented I may have a go, but otherwise I'll implement via multiple devices for the moment.

**Comment by lorenwest** [comment]
The 2.x spec has limited support for node arrays, and I believe this library supports the 2.x flavor of node arrays.

In 3.0 many new concepts were added, one being a better description of node arrays. I'd be happy to consider moving this implementation to 3.0, but don't have a current project that requires the features. I've been waiting for a good ESP8266 or ESP32 implementation of homie 3.x before considering moving to it.

If you are wanting to move this project to 3.0 I'd be happy to help, but I hadn't planned on the work right away.

**Comment by lorenwest** [comment]
Published 3.0.1 with array support
