### ISSUE TITLE
$state value

### ISSUE THREAD

**Issue by lucacalcaterra** [microclimates/homie-device#9]
Hi! 

thanks for you work...

I would write an mqtt client that and use it on Openhab.

In latest release Openhab use Homie Convention but need the $state value (as Homie convention describe). .. without it Openhab not discover the object and throw an error because missing this property.

So, can you add the the $state as Homie specs ?

Thanks! 

Luca

**Comment by lucacalcaterra** [comment]
ps. i noticed there is the $online value. 
Proabably...just enough to rename that to $state ?

**Comment by lorenwest** [comment]
Hi @lucacalcaterra - thanks for your input. The Homie convention has gone through a formal update to a new revision, and I haven't had the time to fully understand the differences. This implements the Homie 2.x version, and 3.x is current.  I would be happy to make updates to the library to bring it to the 3.x level. Would you be willing to go through the updated convention and mark differences between 2.x and 3.x? Arrays are another thing.

**Comment by lucacalcaterra** [comment]
> Hi @lucacalcaterra - thanks for your input. The Homie convention has gone through a formal update to a new revision, and I haven't had the time to fully understand the differences. This implements the Homie 2.x version, and 3.x is current. I would be happy to make updates to the library to bring it to the 3.x level. Would you be willing to go through the updated convention and mark differences between 2.x and 3.x? Arrays are another thing.

The same old story... updates run too fast :-) 

Seems not quite simple to detect all changes... but i'll try if i have time (time, always him )

**Comment by lucacalcaterra** [comment]
ps at this page, is possible to detect changes from 2.0.1 to 3.0.0

https://homieiot.github.io/specification/spec-core-v3_0_0-diff/

**Comment by lorenwest** [comment]
Thanks for the link - unfortunately it's not very helpful. I will probably have to carve out an evening to fully understand the differences, then a week or so to make and test them. 

If you'd like to issue a pull request for this one change I'd be happy to merge and push to npm. If it's additive it shouldn't break backward compatibility.

I think I just saw time - he was passing by.

**Comment by lorenwest** [comment]
Hi @lucacalcaterra, Just published homie-device@3.0.1 with 3.x support including arrays, and, $state

**Comment by lucacalcaterra** [comment]
> Hi @lucacalcaterra, Just published homie-device@3.0.1 with 3.x support including arrays, and, $state

Thanks! I've no time to working on my project... but in next future, i'll try.
